### ISSUE TITLE
Grammar error in translatable string

### ISSUE THREAD

**Issue by fitojb** [lingua-libre/RecordWizard#1]
https://github.com/lingua-libre/RecordWizard/blob/0c92939debff84bce11928217a8a8a6d3e335fa6/i18n/en.json#L66

It’s not “you don’t allowed”, but “you didn’t allow”. In this kind of sentences, the auxiliary verb (i.e., _do_) is the one that gets conjugated in past.

**Comment by 0x010C** [comment]
@fitojb Thanks for raising this issue! :+1: 

Just a note to tell you that issues are moved for now on on the Wikimedia Phabricator issue tracker: https://phabricator.wikimedia.org/project/view/3393/
