### ISSUE TITLE
Translation issue with message MediaWiki:Mwe-recwiz-studio-info-audio/ru

### ISSUE THREAD

**Issue by pashiko** [lingua-libre/RecordWizard#17]
There is a "$1" in the string, but in translation (and in the other languages), it is not replaced by anything. Please see the screencaps below. 

URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=mwe-recwiz-studio-info-audio&group=mwgithub-recordwizard&language=ru

I suppose that the same could happen for one other string: https://translatewiki.net/w/i.php?title=MediaWiki:mwe-recwiz-studio-info-video/en

![Kazam_screenshot_00027](https://user-images.githubusercontent.com/13824846/185813426-148d388c-7693-4b46-b44e-b0cedbb279f2.png)
![Kazam_screenshot_00028](https://user-images.githubusercontent.com/13824846/185813427-4d6d90d1-92e7-4875-b835-f83d921b05c3.png)

**Comment by Poslovitch** [comment]
Hi, closing this since it's already tracked on Phabricator : https://phabricator.wikimedia.org/T307773.

Thank you for your report 🙂
