### ISSUE TITLE
badfilename error when uploading recording of word “Kunstraum Kreuzberg/Bethanien”

### ISSUE THREAD

**Issue by lucaswerkmeister** [lingua-libre/RecordWizard#4]
I used the “Nearby items” feature of the record wizard, and one of the suggested items was [Kunstraum Kreuzberg/Bethanien](http://www.wikidata.org/entity/Q1310526). After recording that word, the recording could not be uploaded; dev tools reveal the following API error:

```json
{
  "upload": {
    "result": "Warning",
    "warnings": {
      "badfilename": "LL-Q188_(deu)-Lucas_Werkmeister-Kunstraum_Kreuzberg-Bethanien.wav"
    },
    "filekey": "redacted.redacted.58.wav",
    "sessionkey": "redacted.redacted.58.wav"
  }
}
```

I’m not sure what exactly is causing the error – the slash in the word seems like the obvious candidate, but the filename mentioned in the warning has no slash, so I’m not sure if that’s the real culprit.

**Comment by 0x010C** [comment]
Hi @lucaswerkmeister,
I just moved this issue to [phabricator](https://phabricator.wikimedia.org/T196879) which is our issue tracker now (I've forgotten to close the issue feature here...).
But thanks for the report!
